Repository CliMA/TurbulenceConvection.jl, pull requests merged in 2021-10, with the labels that each got.

#331 Remove unused and unnecessary code
  integration_tests/utils/Cases.jl
  src/Forcing.jl
  src/Radiation.jl
Labels: house cleaning :broom:, Refactor :gear:

#327 Add docs to construct_tridiag_diffusion_en
  src/Operators.jl
Labels: documentation :ledger:

#334 Add diagnostics dict for io
  integration_tests/utils/main.jl
  src/Variables.jl
  src/diagnostics.jl
Labels: Refactor :gear:, IO :floppy_disk:

#312 remove rain area fractions
  integration_tests/utils/generate_namelist.jl
  integration_tests/utils/mse_tables.jl
  src/EDMF_Environment.jl
  src/EDMF_Rain.jl
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
Labels: Microphysics :cloud_with_snow:

#332 Merge methods into update_aux
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/update_aux.jl
Labels: Restructure :building_construction:

#339 Fix bug with mse computations
  integration_tests/utils/compute_mse.jl
  integration_tests/utils/mse_tables.jl
Labels: Bugfix :bug:

#335 Rename some variable names
  src/EDMF_Environment.jl
  src/EDMF_Rain.jl
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Naming conventions :capital_abcd:

#342 Add aliases, make some structs immutable
  src/EDMF_Environment.jl
  src/EDMF_Rain.jl
  src/EDMF_Updrafts.jl
  src/microphysics_functions.jl
  src/types.jl
Labels: Refactor :gear:

#344 Fix / improve names, add aliases
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:, Naming conventions :capital_abcd:

#345 Improve names, add aliases, move update_aux to its own file
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/update_aux.jl
Labels: Refactor :gear:

#353 Refactor cases to reduce structure assumption
  integration_tests/utils/Cases.jl
Labels: Refactor :gear:

#355 Inline several functions in preparation to fuse operations
  integration_tests/utils/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
  src/turbulence_functions.jl
  src/update_aux.jl
Labels: Refactor :gear:, Restructure :building_construction:

#359 Cleanup, add some docs, fix reference state plots
  docs/src/PlotReferenceStates.jl
  integration_tests/DYCOMS_RF01.jl
  src/Operators.jl
Labels: documentation :ledger:, house cleaning :broom:

#361 Refactor grid constructor
  docs/src/PlotReferenceStates.jl
  integration_tests/utils/main.jl
  src/Grid.jl
Labels: Refactor :gear:

#362 add theta tendency from rain evaporation
  integration_tests/utils/mse_tables.jl
  src/EDMF_Rain.jl
Labels: Bugfix :bug:, Microphysics :cloud_with_snow:

#366 Prep for using ClimaCore fields
  src/Fields.jl
  src/Grid.jl
  src/Operators.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/turbulence_functions.jl
  src/update_aux.jl
Labels: Refactor :gear:

#367 Prep form calculating microphysics tendencies
  src/EDMF_Environment.jl
  src/EDMF_Rain.jl
  src/EDMF_Updrafts.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/microphysics_coupling.jl
  src/microphysics_functions.jl
  src/types.jl
Labels: Microphysics :cloud_with_snow:

#371 Remove some old python primitives
  integration_tests/utils/Cases.jl
  src/EDMF_Environment.jl
  src/EDMF_Updrafts.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
  src/closures/mixing_length.jl
  src/python_primitives.jl
  src/update_aux.jl
Labels: house cleaning :broom:, Refactor :gear:

#378 Rm ref state+grid from surface, use state more, improve names
  integration_tests/utils/Cases.jl
  integration_tests/utils/main.jl
  src/ReferenceState.jl
  src/Surface.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/dycore_api.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#382 Use state more, decouple data structures
  integration_tests/utils/Cases.jl
  integration_tests/utils/main.jl
  src/EDMF_Rain.jl
  src/Fields.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
  src/diagnostics.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#383 Decouple data structures, improve names, rm unused props
  integration_tests/utils/main.jl
  src/EDMF_Environment.jl
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#388 Update dycore API, remove unused props
  src/dycore_api.jl
  src/types.jl
Labels: Refactor :gear:

#399 Fix incorrect qualification of method, improve names
  src/surface_functions.jl
Labels: Bugfix :bug:

#408 Convert more arrays to field, remove up bulkvalues
  integration_tests/utils/main.jl
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
  src/diagnostics.jl
  src/dycore_api.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#409 Remove up tendencies property
  integration_tests/utils/main.jl
  src/Turbulence_PrognosticTKE.jl
  src/dycore_api.jl
  src/types.jl
Labels: Refactor :gear:

#415 Make several grid mean variables fields
  integration_tests/utils/Cases.jl
  integration_tests/utils/main.jl
  src/EDMF_Environment.jl
  src/EDMF_Rain.jl
  src/EDMF_Updrafts.jl
  src/Radiation.jl
  src/Surface.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/diagnostics.jl
  src/dycore_api.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#420 Inline set_values_with_new, rm set_new_with_values
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#421 Make prognostic rain a ClimaCore field
  integration_tests/utils/main.jl
  src/EDMF_Environment.jl
  src/EDMF_Rain.jl
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
  src/diagnostics.jl
  src/dycore_api.jl
  src/types.jl
Labels: Refactor :gear:

#424 Qualify NameList methods, improve plotting warnings
  docs/src/PlotReferenceStates.jl
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/DryBubble.jl
  integration_tests/GABLS.jl
  integration_tests/GATE_III.jl
  integration_tests/LES_driven_SCM.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/SP.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/life_cycle_Tan2018.jl
  integration_tests/utils/compute_mse.jl
  test/perf.jl
  test/profile.jl
  test/runtests.jl
Labels: Refactor :gear:

#427 Use NC.dimnames to determine face/center
  integration_tests/utils/compute_mse.jl
Labels: Refactor :gear:

#416 fix surface sat vap pressure, remove T_freeze overwrite
  integration_tests/GATE_III.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/utils/mse_tables.jl
  integration_tests/utils/parameter_set.jl
  src/Surface.jl
Labels: Microphysics :cloud_with_snow:

#439 support output for dt < 1
  integration_tests/utils/main.jl
Labels: Bugfix :bug:

#477 Remove unused variable, remove overwritten computations
  integration_tests/utils/Cases.jl
Labels: house cleaning :broom:, Refactor :gear:

#480 Use turbconv instead of tc in dycore api
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
  src/diagnostics.jl
  src/dycore_api.jl
  src/update_aux.jl
Labels: Naming conventions :capital_abcd:

#481 Move auxiliary computations to update aux, consolidate io
  integration_tests/utils/mse_tables.jl
  src/EDMF_Environment.jl
  src/EDMF_Precipitation.jl
  src/EDMF_Updrafts.jl
  src/Forcing.jl
  src/Radiation.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/diagnostics.jl
  src/io.jl
  src/update_aux.jl
Labels: Bugfix :bug:, IO :floppy_disk:, Time stepping :clock1:, Diagnostics

#485 Make environment advection explicit
  integration_tests/utils/mse_tables.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Time stepping :clock1:

#486 Make env diffusion explicit
  integration_tests/utils/generate_namelist.jl
  integration_tests/utils/mse_tables.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Time stepping :clock1:
