Repository CliMA/TurbulenceConvection.jl, pull requests merged in 2021-09, with the labels that each got.

#191 Add table of prognostic/diagnostic vars
  README.md
Labels: documentation :ledger:

#192 Fuse grid mean tendencies into single loop
  src/Forcing.jl
  src/Radiation.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/types.jl
Labels: Refactor :gear:

#197 Use RootSolvers.jl in eos
  Project.toml
  integration_tests/utils/mse_tables.jl
  src/TurbulenceConvection.jl
  src/thermodynamic_functions.jl
Labels: enhancement :guitar:

#198 Fix division bug-- need to _divide_ by dz/2
  src/Operators.jl
Labels: Bugfix :bug:

#200 Simplify updraft solve, split another loop
  integration_tests/utils/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Restructure :building_construction:

#202 Move diagnostics computations out of solve_updraft
  src/Turbulence_PrognosticTKE.jl
Labels: Restructure :building_construction:

#205 Add info statements printing max Δmse
  utils/print_new_mse.jl
Labels: Workflow :gear: :ocean:

#206 Replace more operators
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#201 More restructure, update operators, fix grid traversal
  integration_tests/utils/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Restructure :building_construction:

#207 Replace more operators, fix `frac_turb_entr` location
  integration_tests/utils/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Bugfix :bug:, Refactor :gear:

#208 Use percentage change in mse summary
  utils/print_new_mse.jl
Labels: Workflow :gear: :ocean:

#209 Remove `interp2pt`!
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#210 Replace gradient and interpolation with operators
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#211 Avoid more ghost points
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#212 Avoid more ghost points
  integration_tests/utils/mse_tables.jl
  src/EDMF_Updrafts.jl
  src/Radiation.jl
  src/Turbulence_PrognosticTKE.jl
Labels: bug :bug:, Refactor :gear:

#216 Replace more operators
  integration_tests/utils/mse_tables.jl
  src/Operators.jl
  src/turbulence_functions.jl
Labels: Refactor :gear:

#214 Avoid accessing ghost points in Microphysics
  src/EDMF_Rain.jl
  src/Operators.jl
Labels: Restructure :building_construction:

#217 Replace gradient with operator
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#219 Remove `set_bcs`
  integration_tests/utils/Cases.jl
  src/EDMF_Updrafts.jl
  src/Surface.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/set_bcs.jl
Labels: Refactor :gear:

#221 Apply some bug fixes
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
Labels: Bugfix :bug:

#222 Apply some bug fixes
  integration_tests/utils/Cases.jl
  src/EDMF_Updrafts.jl
Labels: Bugfix :bug:

#224 Fix range in reference state construction
  src/ReferenceState.jl
Labels: Bugfix :bug:

#225 Avoid OOB (without ghost points) in buoyancy computation
  src/EDMF_Updrafts.jl
Labels: Refactor :gear:, Logic :brain:

#229 Add an operator, and docs
  docs/src/index.md
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: documentation :ledger:, Bugfix :bug:

#230 Fix indices typo
  integration_tests/utils/Cases.jl
  src/EDMF_Environment.jl
  src/EDMF_Rain.jl
  src/EDMF_Updrafts.jl
  src/Grid.jl
  src/Radiation.jl
  src/ReferenceState.jl
  src/Surface.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/turbulence_functions.jl
Labels: Naming conventions :capital_abcd:, typo :writing_hand:

#220 Apply some bug fixes
  integration_tests/utils/mse_tables.jl
  src/Radiation.jl
Labels: Bugfix :bug:

#231 Remove center_indices and face_indices
  integration_tests/utils/Cases.jl
  src/EDMF_Rain.jl
  src/Grid.jl
  src/Radiation.jl
  src/ReferenceState.jl
  src/Variables.jl
  src/turbulence_functions.jl
Labels: Refactor :gear:

#233 Delete unused code
  src/ReferenceState.jl
Labels: house cleaning :broom:

#234 Fix domain traversal and indexing to use real only
  integration_tests/utils/Cases.jl
Labels: house cleaning :broom:, Bugfix :bug:

#237 Split face/center grid traversal
  src/EDMF_Updrafts.jl
Labels: Bugfix :bug:

#238 Fix range in io for nh pressure
  src/Turbulence_PrognosticTKE.jl
Labels: Bugfix :bug:

#239 Fix index for face BC
  src/Turbulence_PrognosticTKE.jl
Labels: Bugfix :bug:

#240 Fix another grid traversal
  integration_tests/utils/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Bugfix :bug:

#243 Fix daul_c2f_upwind stencil
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Bugfix :bug:

#246 Add use of interpolated field, use correct gradient
  src/Turbulence_PrognosticTKE.jl
Labels: Bugfix :bug:

#218 Restructure grid to not have ghost points
  integration_tests/utils/compute_mse.jl
  integration_tests/utils/generate_namelist.jl
  integration_tests/utils/mse_tables.jl
  src/Fields.jl
  src/Grid.jl
  src/NetCDFIO.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
  src/turbulence_functions.jl
Labels: Refactor :gear:

#251 Fix TC main coordinates in compute_mse
  integration_tests/utils/compute_mse.jl
  test/runtests.jl
Labels: Bugfix :bug:

#250 Clean up cinterior / finterior
  integration_tests/utils/Cases.jl
  integration_tests/utils/compute_mse.jl
  src/EDMF_Environment.jl
  src/EDMF_Rain.jl
  src/EDMF_Updrafts.jl
  src/Grid.jl
  src/Radiation.jl
  src/ReferenceState.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
Labels: house cleaning :broom:, Refactor :gear:

#254 Qualify more methods
  docs/src/ReferenceStates.md
  integration_tests/utils/Cases.jl
  src/EDMF_Environment.jl
  src/Forcing.jl
  src/NetCDFIO.jl
  src/Operators.jl
  src/Radiation.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/turbulence_functions.jl
  src/utility_functions.jl
Labels: Refactor :gear:

#258 Fix 256 bug
  integration_tests/utils/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
  src/turbulence_functions.jl
Labels: Bugfix :bug:

#262 Use latest release of ClimaCore, split project/test env
  .buildkite/pipeline.yml
  .github/workflows/docs.yml
  .gitignore
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  test/Project.toml
Labels: Workflow :gear: :ocean:, Continuous Integration :gear:

#263 Qualify more methods
  docs/src/ReferenceStates.md
  src/Radiation.jl
  src/ReferenceState.jl
  src/TurbulenceConvection.jl
Labels: Refactor :gear:, Coding conventions :computer:

#267 Rename some variables
  integration_tests/utils/Cases.jl
  integration_tests/utils/main.jl
  src/EDMF_Environment.jl
  src/EDMF_Rain.jl
  src/EDMF_Updrafts.jl
  src/Forcing.jl
  src/NetCDFIO.jl
  src/Radiation.jl
  src/Surface.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/types.jl
Labels: Refactor :gear:, Naming conventions :capital_abcd:

#271 Restructure-- split tendencies from solve
  src/Turbulence_PrognosticTKE.jl
  src/turbulence_functions.jl
  src/types.jl
Labels: Refactor :gear:

#273 Split out more tendencies from update
  integration_tests/utils/mse_tables.jl
  src/Operators.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/turbulence_functions.jl
  src/types.jl
Labels: Refactor :gear:

#268 Add function for handling aliased names
  integration_tests/utils/Cases.jl
  integration_tests/utils/compute_mse.jl
  integration_tests/utils/variable_map.jl
  src/Forcing.jl
  src/Radiation.jl
  src/TurbulenceConvection.jl
  src/name_aliases.jl
  src/utility_functions.jl
Labels: Refactor :gear:, Naming conventions :capital_abcd:

#278 Cleanup: remove unused function args
  src/Turbulence_PrognosticTKE.jl
Labels: house cleaning :broom:

#279 Use generic methods in Cases.jl
  integration_tests/utils/Cases.jl
Labels: Improved pattern :building_construction:

#280 Use more generic methods in Surface.jl
  src/Surface.jl
Labels: Refactor :gear:, Improved pattern :building_construction:

#281 Refactor Cases.jl
  docs/src/ReferenceStates.md
  integration_tests/utils/Cases.jl
  integration_tests/utils/main.jl
  integration_tests/utils/mse_tables.jl
  src/types.jl
Labels: Refactor :gear:

#264 Make reference state immutable
  docs/src/PlotReferenceStates.jl
  docs/src/ReferenceStates.md
  integration_tests/utils/Cases.jl
  integration_tests/utils/main.jl
  integration_tests/utils/mse_tables.jl
  src/ReferenceState.jl
Labels: Refactor :gear:

#289 Put eos into a submodule
  integration_tests/utils/Cases.jl
  src/EDMF_Environment.jl
  src/EDMF_Updrafts.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/thermodynamic_functions.jl
  src/turbulence_functions.jl
  src/types.jl
Labels: Refactor :gear:, Thermodynamics :fire:

#291 Make eos_struct immutable
  src/thermodynamic_functions.jl
Labels: Refactor :gear:

#294 Fix contour plot time for tc main
  integration_tests/utils/compute_mse.jl
Labels: Bugfix :bug:

#299 Remove more constant parameters and use climaparameters
  integration_tests/utils/Cases.jl
  integration_tests/utils/main.jl
  integration_tests/utils/mse_tables.jl
  src/Surface.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/closures/mixing_length.jl
  src/parameters.jl
  src/surface_functions.jl
  src/types.jl
Labels: ClimaParameters :control_knobs:

#301 add qr plot in Rico
  integration_tests/utils/mse_tables.jl
Labels: Microphysics :cloud_with_snow:

#302 Refactor Cases.jl
  integration_tests/utils/Cases.jl
Labels: Refactor :gear:

#303 bugfix to cutoff autoconversion
  integration_tests/utils/mse_tables.jl
  src/microphysics_functions.jl
Labels: Microphysics :cloud_with_snow:

#305 use 0-moment microphysics from CM.jl
  Project.toml
  integration_tests/utils/generate_namelist.jl
  integration_tests/utils/mse_tables.jl
  integration_tests/utils/parameter_set.jl
  src/TurbulenceConvection.jl
  src/microphysics_functions.jl
Labels: Microphysics :cloud_with_snow:

#307 Add field data structures
  integration_tests/utils/main.jl
  src/Fields.jl
  src/Grid.jl
  test/Project.toml
Labels: Refactor :gear:, Restructure :building_construction:

#309 Try to improve ci build time
  .buildkite/pipeline.yml
Labels: Workflow :gear: :ocean:, Continuous Integration :gear:

#306 use CM 1-moment microphysics
  integration_tests/utils/generate_namelist.jl
  integration_tests/utils/mse_tables.jl
  integration_tests/utils/parameter_set.jl
  src/EDMF_Environment.jl
  src/EDMF_Rain.jl
  src/EDMF_Updrafts.jl
  src/TurbulenceConvection.jl
  src/microphysics_functions.jl
  src/types.jl
Labels: Microphysics :cloud_with_snow:

#313 Clean up Cases.jl, call satadjust outside of initialize_profiles
  integration_tests/utils/Cases.jl
  integration_tests/utils/main.jl
  integration_tests/utils/mse_tables.jl
Labels: house cleaning :broom:, Refactor :gear:

#314 Further refactor cases--remove unnecessary calls
  integration_tests/utils/Cases.jl
Labels: house cleaning :broom:, Refactor :gear:

#317 Refactor Surface.jl
  integration_tests/utils/mse_tables.jl
  src/Surface.jl
Labels: Refactor :gear:

#318 fix bug TRMM init
  integration_tests/utils/Cases.jl
  integration_tests/utils/mse_tables.jl
Labels: Bugfix :bug:

#320 Use fields for reference state, add field io, compute_mse bugfixes
  docs/src/PlotReferenceStates.jl
  integration_tests/utils/Cases.jl
  integration_tests/utils/compute_mse.jl
  integration_tests/utils/main.jl
  src/Fields.jl
  src/NetCDFIO.jl
  src/ReferenceState.jl
  src/TurbulenceConvection.jl
  src/diagnostics.jl
  src/dycore_api.jl
  src/name_aliases.jl
Labels: Bugfix :bug:, Refactor :gear:, Restructure :building_construction:

#326 Fuse some loops
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:, Restructure :building_construction:

#328 Add update_aux to prep fusing more ops
  src/EDMF_Environment.jl
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:, Restructure :building_construction:
