Repository CliMA/TurbulenceConvection.jl, pull requests merged in 2021-12, with the labels that each got.

#594 Use more ClimaCore operators
  src/update_aux.jl
Labels: Refactor :gear:

#599 Hoist getproperty outside of broadcast, move zero-out before up loop
  src/Turbulence_PrognosticTKE.jl
Labels: Performance :rocket:, Bugfix :bug:

#600 Unify gm covar expression
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#604 Remove closure, capture sol at tmin/tmax
  integration_tests/utils/main.jl
Labels: Visualization :art:, Post processing :gear:

#606 Use more ClimaCore operators
  integration_tests/utils/mse_tables.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#608 Use more ClimaCore operators
  docs/src/index.md
  src/Operators.jl
  src/Radiation.jl
Labels: Refactor :gear:

#613 Shrink Rico timestep to make more stable
  integration_tests/utils/generate_namelist.jl
  integration_tests/utils/mse_tables.jl
Labels: Numerical Stability

#610 Use more ClimaCore operators
  integration_tests/utils/mse_tables.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#614 Add SciMLBase to test env
  test/Project.toml
Labels: Tests :warning:

#615 Reorganize folders
  docs/src/PlotReferenceStates.jl
  driver/Artifacts.toml
  driver/Cases.jl
  driver/generate_namelist.jl
  driver/initial_conditions.jl
  driver/main.jl
  driver/parameter_set.jl
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/DryBubble.jl
  integration_tests/GABLS.jl
  integration_tests/GATE_III.jl
  integration_tests/LES_driven_SCM.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/SP.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/life_cycle_Tan2018.jl
  perf/common.jl
  post_processing/Artifacts.toml
  post_processing/compute_mse.jl
  post_processing/mse_tables.jl
  post_processing/post_run_tests.jl
  test/runtests.jl
  utils/print_new_mse.jl
Labels: Refactor :gear:, Naming conventions :capital_abcd:

#609 Use more ClimaCore operators
  driver/main.jl
  post_processing/mse_tables.jl
  src/Operators.jl
  src/turbulence_functions.jl
  src/update_aux.jl
Labels: Refactor :gear:

#617 Use more ClimaCore operators
  driver/main.jl
  src/Radiation.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#611 Move CFL computations to callback
  driver/main.jl
  src/EDMF_Precipitation.jl
  src/Turbulence_PrognosticTKE.jl
  src/update_aux.jl
Labels: Refactor :gear:

#620 Move dt_max computations into callback
  driver/main.jl
  post_processing/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#624 Use more ClimaCore operators
  driver/Cases.jl
  driver/main.jl
  post_processing/mse_tables.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
  src/update_aux.jl
Labels: Refactor :gear:

#625 Move updraft_top to update_aux!
  diagnostics/compute_diagnostics.jl
  post_processing/mse_tables.jl
  src/update_aux.jl
Labels: bug :bug:, Bugfix :bug:

#626 Add perf benchmark to buildkite
  .buildkite/pipeline.yml
  perf/perf.jl
Labels: Performance monitoring :rocket: :computer:

#630 Fix some type instabilities
  src/closures/entr_detr.jl
  src/utility_functions.jl
Labels: Performance :rocket:

#632 Reduce allocations
  driver/main.jl
  src/Turbulence_PrognosticTKE.jl
  src/turbulence_functions.jl
  src/update_aux.jl
Labels: Performance :rocket:

#635 Make and ensure param_set is isbits
  docs/Project.toml
  driver/generate_namelist.jl
  driver/parameter_set.jl
Labels: Performance :rocket:

#629 Reorganize / split EDMF from dycore
  driver/callbacks.jl
  driver/dycore.jl
  driver/main.jl
  perf/common.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/variables.jl
Labels: Restructure :building_construction:

#636 move massflux src for cov to diagnostic
  diagnostics/compute_diagnostics.jl
  post_processing/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
  src/update_aux.jl
Labels: house cleaning :broom:, Memory :brain:

#634 Avoid collecting mapped field
  src/Grid.jl
  src/turbulence_functions.jl
Labels: Performance :rocket:, Refactor :gear:

#646 Concretize type, hoist vars from loop, avoid redefining CC operators
  src/types.jl
  src/update_aux.jl
Labels: Performance :rocket:, Refactor :gear:

#647 Fix type instability
  src/types.jl
Labels: Performance :rocket:

#650 Fix CI, update compat and CLIMAParameters call func call
  Project.toml
  driver/generate_namelist.jl
  driver/parameter_set.jl
  src/surface_functions.jl
  test/Project.toml
Labels: Continuous Integration :gear:, Microphysics :cloud_with_snow:

#652 Improve/unify some names
  driver/main.jl
  perf/common.jl
Labels: Naming conventions :capital_abcd:

#655 Add type parameters to Simulation1d
  driver/main.jl
Labels: Performance :rocket:

#656 Improve / unify names
  driver/main.jl
Labels: Naming conventions :capital_abcd:

#536 add microphysics sources
  driver/generate_namelist.jl
  driver/parameter_set.jl
  post_processing/mse_tables.jl
  src/EDMF_Precipitation.jl
  src/microphysics_coupling.jl
Labels: Microphysics :cloud_with_snow:

#661 Start removing TS, + cleanup
  diagnostics/compute_diagnostics.jl
  driver/Cases.jl
  driver/callbacks.jl
  driver/initial_conditions.jl
  driver/main.jl
  perf/common.jl
  src/Turbulence_PrognosticTKE.jl
  src/update_aux.jl
Labels: Refactor :gear:

#662 Remove moisture comparison in GABLS to fix CI
  post_processing/mse_tables.jl
Labels: Correctness :pencil2:, Continuous Integration :gear:

#663 Bump version for new release
  Project.toml
Labels: Release

#657 replace dependency DiffEq by StochasticDiffEq
  Project.toml
  src/TurbulenceConvection.jl
  src/closures/entr_detr.jl
  src/stochastic_closures.jl
  test/Project.toml
Labels: Dependencies :spider_web:

#670 Make CFL computation based on local dz
  driver/callbacks.jl
  src/Fields.jl
Labels: enhancement :guitar:

#669 Use ClimaCore vertical integrals for lwp etc
  diagnostics/compute_diagnostics.jl
  driver/callbacks.jl
  driver/initial_conditions.jl
  src/Turbulence_PrognosticTKE.jl
  src/io.jl
  src/types.jl
Labels: enhancement :guitar:

#673 Add invalidations script
  .buildkite/pipeline.yml
  perf/invalidations.jl
  test/Project.toml
Labels: Performance monitoring :rocket: :computer:

#674 Add explicit show to last tree element
  perf/invalidations.jl
Labels: Performance monitoring :rocket: :computer:

#676 Remove unused variables
  src/Grid.jl
  src/parameters.jl
Labels: house cleaning :broom:

#675 Add flame graph script to perf folder
  perf/flame.jl
Labels: Performance monitoring :rocket: :computer:

#622 Add changelog to TagBot GHA
  .github/workflows/TagBot.yml
Labels: Automation :robot:

#677 Remove more use of TimeStepping
  driver/Cases.jl
  driver/callbacks.jl
  driver/main.jl
  src/EDMF_Precipitation.jl
  src/Turbulence_PrognosticTKE.jl
  src/io.jl
Labels: Refactor :gear:

#678 Bump version
  Project.toml
Labels: Release

#679 Fix CFL dz bug
  Project.toml
  driver/callbacks.jl
Labels: bugfix

#680 Move cloud base, top, and cover to diagnostics
  diagnostics/compute_diagnostics.jl
  driver/callbacks.jl
  driver/initial_conditions.jl
  driver/main.jl
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
  src/io.jl
  src/types.jl
Labels: Refactor :gear:

#681 Make ForcingBase immutable
  driver/Cases.jl
  driver/main.jl
  src/types.jl
Labels: Refactor :gear:

#683 Make LESData immutable
  src/types.jl
Labels: Refactor :gear:

#684 Make RadiationBase immutable
  driver/Cases.jl
  driver/main.jl
  src/Radiation.jl
  src/types.jl
Labels: Refactor :gear:

#685 Make some types more concrete
  src/NetCDFIO.jl
  src/types.jl
Labels: Refactor :gear:

#686 Cache gauss quad in sgs env thermo
  src/EDMF_Environment.jl
  src/types.jl
Labels: Performance :rocket:, Performance monitoring :rocket: :computer:

#687 Decompose run for more focused perf monitor config
  driver/main.jl
  perf/common.jl
  perf/flame.jl
Labels: Performance monitoring :rocket: :computer:

#689 Reduce number of inference triggers
  src/EDMF_Environment.jl
  src/update_aux.jl
Labels: Performance :rocket:, Refactor :gear:

#690 Use types and dispatch instead of strings
  diagnostics/compute_diagnostics.jl
  driver/initial_conditions.jl
  driver/main.jl
  src/EDMF_Environment.jl
  src/EDMF_Precipitation.jl
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
  src/io.jl
  src/microphysics_coupling.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:, Improved pattern :building_construction:

#691 Reduce number of inference triggers
  driver/initial_conditions.jl
  perf/inference_triggers.jl
  src/Turbulence_PrognosticTKE.jl
  src/update_aux.jl
Labels: Performance :rocket:, Refactor :gear:

#692 Rm CCO redef, more type space, +hoist, type annot
  diagnostics/compute_diagnostics.jl
  driver/Cases.jl
  perf/inference_triggers.jl
  src/EDMF_Environment.jl
  src/EDMF_Precipitation.jl
  src/EDMF_Updrafts.jl
  src/Grid.jl
  src/NetCDFIO.jl
  src/Turbulence_PrognosticTKE.jl
  src/update_aux.jl
Labels: Performance :rocket:, Performance monitoring :rocket: :computer:

#693 Remove several unused edmf variables
  driver/Cases.jl
  driver/generate_namelist.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
  src/update_aux.jl
Labels: house cleaning :broom:, Refactor :gear:

#694 Make EDMF_PrognosticTKE immutable
  driver/callbacks.jl
  src/TimeStepping.jl
  src/types.jl
Labels: Refactor :gear:

#695 Improve func findability, hoist code, renaming
  diagnostics/compute_diagnostics.jl
  driver/Cases.jl
  driver/callbacks.jl
  driver/initial_conditions.jl
  driver/main.jl
  perf/common.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:, Naming conventions :capital_abcd:

#696 Add new immutable surface types
  docs/Project.toml
  driver/Cases.jl
  driver/initial_conditions.jl
  driver/main.jl
  src/Surface.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:, Improved pattern :building_construction:

#697 Use FixedSurfaceFlux in update
  docs/Project.toml
  driver/Cases.jl
  driver/parameter_set.jl
  src/Surface.jl
  src/types.jl
Labels: Refactor :gear:

#698 Move use of ArtifactWrappers inside function
  driver/generate_namelist.jl
  integration_tests/LES_driven_SCM.jl
Labels: Refactor :gear:
