Repository CliMA/TurbulenceConvection.jl, pull requests merged in 2021-08, with the labels that each got.

#65 Refactor compute_zbl_qt_grad
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
Labels: Refactor :gear:

#66 Add higher order moments
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/GABLS.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/utils/compute_mse.jl
  integration_tests/utils/variable_map.jl
Labels: Visualization :art:

#70 Hard code pottemp methods to eos and remove entropy option
  src/EDMF_Environment.jl
  src/EDMF_Updrafts.jl
  src/ReferenceState.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/thermodynamic_functions.jl
  src/types.jl
Labels: Refactor :gear:

#75 Fix field locations
  src/types.jl
Labels: Bugfix :bug:

#74 Use bcs and avoid accessing ghost points
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: enhancement :guitar:

#78 Use more grid and field abstractions
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/turbulence_functions.jl
Labels: Refactor :gear:

#69 use parse_namelist
  src/TurbulenceConvection.jl
  src/types.jl
Labels: Refactor :gear:

#77 Ignore artifact file to avoid git conflicts
  .gitignore
  integration_tests/utils/Artifacts.toml
Labels: Workflow :gear: :ocean:

#76 Fix and improve dycoms radiation
  integration_tests/DYCOMS_RF01.jl
  src/Radiation.jl
Labels: enhancement :guitar:

#83 Abstract cent/face surface/toa indices
  integration_tests/utils/Cases.jl
  src/EDMF_Environment.jl
  src/EDMF_Updrafts.jl
  src/Fields.jl
  src/Grid.jl
  src/Surface.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/turbulence_functions.jl
Labels: Refactor :gear:

#84 Use parse_namelist in timestepping constructor
  src/TimeStepping.jl
Labels: Refactor :gear:

#81 Remove `revxrange`
  src/EDMF_Rain.jl
  src/python_primitives.jl
Labels: Refactor :gear:

#86 Make indexing more consistent
  src/EDMF_Rain.jl
  src/Forcing.jl
  src/Grid.jl
  src/Operators.jl
  src/ReferenceState.jl
  src/Turbulence_PrognosticTKE.jl
  src/turbulence_functions.jl
  src/utility_functions.jl
Labels: Refactor :gear:

#85 Convert to 1-based indexing
  integration_tests/utils/Cases.jl
  src/EDMF_Environment.jl
  src/EDMF_Updrafts.jl
  src/Grid.jl
  src/ReferenceState.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/python_primitives.jl
  src/turbulence_functions.jl
Labels: Refactor :gear:

#87 Remove THL, and replace with H
  integration_tests/utils/Cases.jl
  src/EDMF_Environment.jl
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/types.jl
Labels: house cleaning :broom:

#89 Remove some calls to off_arr
  src/EDMF_Environment.jl
  src/EDMF_Updrafts.jl
  src/Radiation.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/python_primitives.jl
Labels: house cleaning :broom:

#91 Reorganize code and remove some python primitives
  integration_tests/utils/Cases.jl
  integration_tests/utils/main.jl
  src/EDMF_Environment.jl
  src/EDMF_Rain.jl
  src/EDMF_Updrafts.jl
  src/Fields.jl
  src/Grid.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/python_primitives.jl
  src/set_bcs.jl
  src/types.jl
Labels: house cleaning :broom:, Refactor :gear:

#67 Move entrainment fact to climaparams method call
  integration_tests/utils/parameter_set.jl
  src/Turbulence_PrognosticTKE.jl
  src/turbulence_functions.jl
  src/types.jl
Labels: calibration :dart:

#92 Remove OffsetArrays dep, qualify methods, cleanup
  Project.toml
  src/EDMF_Environment.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/python_primitives.jl
  src/utility_functions.jl
Labels: house cleaning :broom:

#97 Remove 1.5 CI
  .github/workflows/ci.yml
  bors.toml
Labels: Tests :warning:, Workflow :gear: :ocean:

#25 Use Thermodynamics.jl for reference state profiles
  Project.toml
  docs/src/ReferenceStates.md
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/GABLS.jl
  integration_tests/GATE_III.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  src/ReferenceState.jl
  src/TurbulenceConvection.jl
Labels: Thermodynamics :fire:

#99 Make les comparison optional, + more cases plots
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/DryBubble.jl
  integration_tests/GABLS.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/SP.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/life_cycle_Tan2018.jl
  integration_tests/utils/compute_mse.jl
Labels: Tests :warning:, Continuous Integration :gear:

#108 Add option for optional tc main in plots
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/DryBubble.jl
  integration_tests/GABLS.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/SP.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/life_cycle_Tan2018.jl
  integration_tests/utils/compute_mse.jl
Labels: Visualization :art:

#109 Add mse wrapper to make optional files flexible
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/DryBubble.jl
  integration_tests/GABLS.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/SP.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/life_cycle_Tan2018.jl
  integration_tests/utils/compute_mse.jl
Labels: Refactor :gear:, Visualization :art:

#110 Add main comparison in CI
  .buildkite/pipeline.yml
  Project.toml
  integration_tests/utils/compute_mse.jl
  utils/move_output.jl
Labels: Continuous Integration :gear:

#112 Fix tc main results path
  integration_tests/utils/compute_mse.jl
Labels: Continuous Integration :gear:

#117 Make sure that qt in updraft is non negative
  src/Turbulence_PrognosticTKE.jl
Labels: Model Robustness :robot:

#118 Remove some python primitives
  integration_tests/utils/Cases.jl
  src/EDMF_Environment.jl
  src/EDMF_Updrafts.jl
  src/Radiation.jl
  src/Surface.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/closures/entr_detr.jl
  src/closures/nondimensional_exchange_functions.jl
  src/closures/perturbation_pressure.jl
  src/microphysics_functions.jl
  src/python_primitives.jl
  src/surface_functions.jl
  src/thermodynamic_functions.jl
  src/turbulence_functions.jl
Labels: house cleaning :broom:, Refactor :gear:

#116 Group plots
  integration_tests/utils/compute_mse.jl
  integration_tests/utils/variable_map.jl
Labels: Visualization :art:, Continuous Integration :gear:

#127 Fix tc main commit sha
  Project.toml
  integration_tests/utils/compute_mse.jl
Labels: Bugfix :bug:

#126 Squeeze out space in profile plots
  integration_tests/utils/compute_mse.jl
Labels: Visualization :art:

#113 Add Bomex as unit test for codecov
  .buildkite/pipeline.yml
  .github/workflows/CodeCov.yml
  test/Project.toml
  test/runtests.jl
Labels: Tests :warning:, Continuous Integration :gear:

#129 Merge mse tables->1 file, print mse table post run
  .buildkite/pipeline.yml
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/DryBubble.jl
  integration_tests/GABLS.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/SP.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/life_cycle_Tan2018.jl
  integration_tests/utils/compute_mse.jl
  integration_tests/utils/mse_tables.jl
  utils/print_new_mse.jl
Labels: Workflow :gear: :ocean:

#128 Use dispatch for entr-detr, + DocStringExtensions
  Project.toml
  docs/Project.toml
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/closures/entr_detr.jl
  src/closures/nondimensional_exchange_functions.jl
  src/types.jl
  src/utility_functions.jl
Labels: documentation :ledger:, Improved pattern :building_construction:

#134 Add internal experimental clima parameters
  docs/src/index.md
  integration_tests/utils/parameter_set.jl
  src/ClimaParams.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/closures/entr_detr.jl
  src/types.jl
Labels: ClimaParameters :control_knobs:

#132 Remove const g parameter -> use CLIMAParameters
  integration_tests/utils/Cases.jl
  integration_tests/utils/mse_tables.jl
  src/EDMF_Environment.jl
  src/EDMF_Rain.jl
  src/EDMF_Updrafts.jl
  src/Surface.jl
  src/Turbulence_PrognosticTKE.jl
  src/Variables.jl
  src/microphysics_functions.jl
  src/parameters.jl
  src/surface_functions.jl
  src/thermodynamic_functions.jl
  src/turbulence_functions.jl
  src/types.jl
Labels: ClimaParameters :control_knobs:

#131 add Ri and Pr functions
  integration_tests/utils/generate_namelist.jl
  integration_tests/utils/parameter_set.jl
  src/Turbulence_PrognosticTKE.jl
  src/turbulence_functions.jl
Labels: ClimaParameters :control_knobs:

#148 Make mse tables easier to copy-paste
  integration_tests/utils/mse_tables.jl
  utils/print_new_mse.jl
Labels: Workflow :gear: :ocean:

#150 Use ∇f2c operator
  integration_tests/utils/mse_tables.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#151 Update readme
  README.md
Labels: documentation :ledger:

#154 Change ∇_upwind to ∇_onesided and use bcs
  src/Forcing.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#170 Use more discrete operators
  integration_tests/utils/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#173 Add fcut and f∇, and use appropriately
  integration_tests/utils/mse_tables.jl
  src/Forcing.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Bugfix :bug:, Naming conventions :capital_abcd:

#175 Add bcs to interpf2c
  integration_tests/utils/Cases.jl
  src/Operators.jl
Labels: Refactor :gear:

#176 Make advection operators use bcs, fix index in method call
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
  src/utility_functions.jl
Labels: Refactor :gear:

#177 Use bcs with operators in upwind_advection_velocity
  integration_tests/utils/mse_tables.jl
  src/Forcing.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#179 House cleaning, use unicode
  src/Surface.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
Labels: house cleaning :broom:, Naming conventions :capital_abcd:

#181 Add upwind operator, remove use of interp2pt in Operators
  src/Forcing.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#182 Replace interp2pt with bc interp ops
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#183 Fix diagnostics traversal
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Bugfix :bug:

#185 Add aliases to shorten expressions
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#186 Restructure main to have single update function
  integration_tests/utils/Cases.jl
  integration_tests/utils/main.jl
  integration_tests/utils/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Restructure :building_construction:

#188 Fix regression test for cases without LES data
  integration_tests/utils/compute_mse.jl
  integration_tests/utils/mse_tables.jl
Labels: Bugfix :bug:

#189 Silence codecov annotations
  .github/codecov.yml
Labels: Workflow :gear: :ocean:
