Repository CliMA/TurbulenceConvection.jl, pull requests merged in 2021-11, with the labels that each got.

#487 Replace environment matrix inverse with explicit update
  integration_tests/utils/mse_tables.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
Labels: Time stepping :clock1:

#488 Solve for conservative, not primitive, prognostic env variables
  integration_tests/utils/initial_conditions.jl
  integration_tests/utils/main.jl
  integration_tests/utils/mse_tables.jl
  src/EDMF_Environment.jl
  src/Turbulence_PrognosticTKE.jl
  src/diagnostics.jl
  src/update_aux.jl
Labels: Time stepping :clock1:

#490 Bump version for new release
  Project.toml
Labels: Release

#489 fix the use of env_b from previous timestep in buoyancy extrap
  src/update_aux.jl
Labels: Refactor :gear:

#491 Reduce allocations
  src/Turbulence_PrognosticTKE.jl
  src/update_aux.jl
Labels: Performance :rocket:, Refactor :gear:

#492 Try to improve perf in mix len, rm mutable array
  integration_tests/utils/mse_tables.jl
  src/closures/mixing_length.jl
Labels: Performance :rocket:, Refactor :gear:

#497 Make mixing length a ClimaCore field
  integration_tests/utils/main.jl
  src/Turbulence_PrognosticTKE.jl
  src/closures/mixing_length.jl
  src/diagnostics.jl
  src/io.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#494 Make precip variables ClimaCore fields, rm unused funcs, cleanup
  integration_tests/utils/main.jl
  src/EDMF_Precipitation.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
Labels: Refactor :gear:

#498 Make some diagnostic quantities ClimaCore fields
  integration_tests/utils/main.jl
  src/diagnostics.jl
  src/dycore_api.jl
  src/io.jl
Labels: Refactor :gear:

#501 Make `term_vel` a ClimaCore field
  integration_tests/utils/main.jl
  src/EDMF_Precipitation.jl
Labels: Refactor :gear:

#500 Make virtual temperature a ClimaCore field
  integration_tests/utils/Cases.jl
  integration_tests/utils/initial_conditions.jl
  integration_tests/utils/main.jl
  src/Surface.jl
  src/turbulence_functions.jl
  src/update_aux.jl
Labels: Refactor :gear:, Naming conventions :capital_abcd:

#509 lets see if it helps CI
  integration_tests/utils/mse_tables.jl
Labels: Microphysics :cloud_with_snow:

#510 Make compute_mse work with zero contour fields again
  integration_tests/utils/compute_mse.jl
  integration_tests/utils/mse_tables.jl
Labels: Bugfix :bug:, Microphysics :cloud_with_snow:

#514 add snow advection
  integration_tests/utils/main.jl
  src/EDMF_Environment.jl
  src/EDMF_Precipitation.jl
  src/EDMF_Updrafts.jl
  src/microphysics_coupling.jl
  src/types.jl
Labels: Microphysics :cloud_with_snow:

#512 Make some rain variables ClimaCore fields
  integration_tests/utils/main.jl
  src/EDMF_Environment.jl
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
  src/diagnostics.jl
  src/dycore_api.jl
  src/io.jl
  src/types.jl
Labels: Refactor :gear:, Microphysics :cloud_with_snow:

#513 move env_thermo precip arrays to aux
  integration_tests/utils/main.jl
  src/EDMF_Environment.jl
  src/Turbulence_PrognosticTKE.jl
  src/diagnostics.jl
  src/types.jl
Labels: Microphysics :cloud_with_snow:

#515 Additional data structs for snow
  integration_tests/utils/main.jl
  src/EDMF_Environment.jl
  src/EDMF_Precipitation.jl
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
  src/diagnostics.jl
  src/io.jl
  src/types.jl
Labels: Microphysics :cloud_with_snow:

#516 Reduce allocations, move some variables to climacore fields
  integration_tests/utils/Cases.jl
  integration_tests/utils/main.jl
  src/Surface.jl
  src/Turbulence_PrognosticTKE.jl
  src/turbulence_functions.jl
  src/update_aux.jl
Labels: Memory :brain:, Performance :rocket:, Refactor :gear:

#520 Use ClimaCore operators in get_GMV_CoVar
  src/Turbulence_PrognosticTKE.jl
Labels: Performance :rocket:, Refactor :gear:

#519 Time runs, which should be, ideally, non-allocating
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/DryBubble.jl
  integration_tests/GABLS.jl
  integration_tests/GATE_III.jl
  integration_tests/LES_driven_SCM.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/SP.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/life_cycle_Tan2018.jl
  test/runtests.jl
Labels: Performance :rocket:

#517 use latent heat const with T
  integration_tests/utils/Cases.jl
  integration_tests/utils/mse_tables.jl
  src/Surface.jl
  src/microphysics_coupling.jl
  src/surface_functions.jl
Labels: Consistency :dart:

#523 Make more variables ClimaCore fields
  integration_tests/utils/main.jl
  src/Turbulence_PrognosticTKE.jl
  src/diagnostics.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#524 Cleanup - Remove unused type and repeated computations
  src/EDMF_Precipitation.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
Labels: house cleaning :broom:, Refactor :gear:

#527 Make more variables ClimaCore fields
  integration_tests/utils/main.jl
  src/EDMF_Environment.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#529 Make more variables ClimaCore fields
  integration_tests/utils/main.jl
  src/Turbulence_PrognosticTKE.jl
  src/diagnostics.jl
  src/io.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#528 fix w third moment bug
  src/Turbulence_PrognosticTKE.jl
Labels: Bugfix :bug:

#530 Make more variables ClimaCore fields
  integration_tests/utils/main.jl
  src/Turbulence_PrognosticTKE.jl
  src/diagnostics.jl
  src/io.jl
  src/types.jl
Labels: Refactor :gear:

#531 Make more variables ClimaCore fields
  integration_tests/utils/initial_conditions.jl
  integration_tests/utils/main.jl
  src/NetCDFIO.jl
  src/diagnostics.jl
  src/io.jl
  src/types.jl
  src/update_aux.jl
Labels: house cleaning :broom:, Refactor :gear:

#532 Make more variables ClimaCore fields
  integration_tests/utils/Cases.jl
  integration_tests/utils/main.jl
  src/Fields.jl
  src/Forcing.jl
  src/NetCDFIO.jl
  src/Radiation.jl
  src/Turbulence_PrognosticTKE.jl
  src/closures/entr_detr.jl
  src/diagnostics.jl
  src/io.jl
  src/types.jl
Labels: Refactor :gear:

#533 Cleanup unused methods
  integration_tests/utils/Cases.jl
  src/Fields.jl
  src/types.jl
Labels: house cleaning :broom:, Refactor :gear:

#535 Add bulk dycore getter method
  integration_tests/utils/initial_conditions.jl
  src/Turbulence_PrognosticTKE.jl
  src/diagnostics.jl
  src/dycore_api.jl
  src/update_aux.jl
Labels: Refactor :gear:

#534 Use ClimaCore operators
  integration_tests/utils/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Performance :rocket:, Refactor :gear:

#521 Use ClimaCore operators in compute_covariance_shear
  integration_tests/utils/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Performance :rocket:, Refactor :gear:

#537 Add option to skip IO, for perf analysis
  integration_tests/utils/generate_namelist.jl
  integration_tests/utils/main.jl
Labels: IO :floppy_disk:

#538 Update perf/allocations analysis tools
  .buildkite/pipeline.yml
  perf/alloc_per_case.jl
  perf/allocs.jl
  perf/common.jl
  perf/perf.jl
  perf/profile.jl
  test/Project.toml
  test/perf.jl
  test/profile.jl
Labels: Memory :brain:, Performance :rocket:

#539 Reduce allocations
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
  src/update_aux.jl
Labels: Memory :brain:, Performance :rocket:

#542 Add title to allocations plot
  perf/allocs.jl
Labels: Visualization :art:

#541 Reduce allocations
  integration_tests/utils/main.jl
  src/update_aux.jl
Labels: Memory :brain:, Performance :rocket:, Refactor :gear:

#543 Reduce allocations
  integration_tests/utils/main.jl
  src/Turbulence_PrognosticTKE.jl
  src/update_aux.jl
Labels: Memory :brain:, Performance :rocket:, Refactor :gear:

#545 Bump version for new release
  Project.toml
Labels: Release

#544 Reduce allocations, use ClimaCore operators
  integration_tests/utils/main.jl
  integration_tests/utils/mse_tables.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Memory :brain:, Performance :rocket:, Refactor :gear:

#549 Move purely diagnostic fields outside of src
  diagnostics/compute_diagnostics.jl
  integration_tests/utils/main.jl
  perf/allocs.jl
  perf/common.jl
  src/diagnostics.jl
  src/dycore_api.jl
Labels: Defensive programming :crossed_swords:, Refactor :gear:, Breaking changes :boom:

#552 Change update interface, rename to step
  integration_tests/utils/main.jl
  perf/common.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
Labels: Refactor :gear:

#553 Add compat entries to test env
  test/Project.toml
Labels: Bugfix :bug:, Continuous Integration :gear:

#555 Performance patch
  src/EDMF_Updrafts.jl
  src/Fields.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Performance :rocket:, Refactor :gear:

#554 Make diag dict field entry a state-accepting func
  diagnostics/compute_diagnostics.jl
  docs/src/PlotReferenceStates.jl
  integration_tests/utils/main.jl
  src/diagnostics.jl
Labels: Refactor :gear:

#473 Use OrdinaryDiffEq.jl for timestepping
  integration_tests/utils/main.jl
  integration_tests/utils/mse_tables.jl
  perf/alloc_per_case.jl
  perf/common.jl
  perf/perf.jl
  perf/profile.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Time stepping :clock1:

#558 Use ClimaCore operators, reduce allocs
  integration_tests/utils/mse_tables.jl
  src/Operators.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Memory :brain:, Performance :rocket:, Refactor :gear:

#560 Add type annotations
  src/turbulence_functions.jl
Labels: Performance :rocket:, Refactor :gear:

#561 Use ClimaCore operators
  integration_tests/utils/main.jl
  integration_tests/utils/mse_tables.jl
  src/update_aux.jl
Labels: Refactor :gear:

#562 Make EDMF model more concrete
  integration_tests/utils/mse_tables.jl
  src/closures/buoyancy_gradients.jl
  src/types.jl
Labels: Performance :rocket:, Refactor :gear:

#564 Make more variables climacore fields
  integration_tests/utils/main.jl
  src/update_aux.jl
Labels: Refactor :gear:

#565 Replace vanishing subdomain gradients with ClimaCore operators
  integration_tests/utils/main.jl
  integration_tests/utils/mse_tables.jl
  src/Operators.jl
  src/update_aux.jl
Labels: Refactor :gear:

#567 Add iterator for traversing grid
  integration_tests/utils/mse_tables.jl
  src/EDMF_Precipitation.jl
  src/Grid.jl
Labels: Memory :brain:, Performance :rocket:, Refactor :gear:, Upstream induced changes :point_up:

#566 Add type annotations to pressure funcs
  src/closures/perturbation_pressure.jl
Labels: Refactor :gear:

#559 Reduce allocations in MinDisspLen
  integration_tests/utils/main.jl
  src/closures/mixing_length.jl
  src/types.jl
  src/update_aux.jl
Labels: Memory :brain:, Performance :rocket:, Refactor :gear:

#569 Replace some operators with ClimaCore operators, remove unused operators
  diagnostics/compute_diagnostics.jl
  src/Operators.jl
Labels: house cleaning :broom:, Refactor :gear:

#568 Try to improve type inference
  src/update_aux.jl
Labels: Performance :rocket:, Refactor :gear:

#572 Replace more operators with ClimaCore operators
  docs/bibliography.bib
  docs/src/index.md
  integration_tests/utils/mse_tables.jl
  src/Operators.jl
  src/closures/perturbation_pressure.jl
  src/update_aux.jl
Labels: house cleaning :broom:, Refactor :gear:

#573 Use more ClimaCore operators
  integration_tests/utils/main.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#575 Add post-run tests, error if we do not run to t_max
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/DryBubble.jl
  integration_tests/GABLS.jl
  integration_tests/GATE_III.jl
  integration_tests/LES_driven_SCM.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/SP.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/life_cycle_Tan2018.jl
  integration_tests/utils/generate_namelist.jl
  integration_tests/utils/main.jl
  integration_tests/utils/mse_tables.jl
  integration_tests/utils/post_run_tests.jl
Labels: Regression prevention :crossed_swords:

#578 Improve inference, hoist out getproperty
  integration_tests/utils/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Performance :rocket:, Refactor :gear:, Upstream induced changes :point_up:

#580 Use more ClimaCore operators
  src/EDMF_Precipitation.jl
Labels: Performance :rocket:, Refactor :gear:

#581 Error on aborted simulations after solution export
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/DryBubble.jl
  integration_tests/GABLS.jl
  integration_tests/GATE_III.jl
  integration_tests/LES_driven_SCM.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/SP.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/life_cycle_Tan2018.jl
  integration_tests/utils/main.jl
  integration_tests/utils/post_run_tests.jl
  test/runtests.jl
Labels: Tests :warning:, Breaking changes :boom:, Post processing :gear:

#582 Sequential tests -> nested tests
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/DryBubble.jl
  integration_tests/GABLS.jl
  integration_tests/GATE_III.jl
  integration_tests/LES_driven_SCM.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/SP.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/life_cycle_Tan2018.jl
Labels: Tests :warning:

#579 Use linear interpolation for comparisons and mse
  integration_tests/utils/compute_mse.jl
  integration_tests/utils/mse_tables.jl
Labels: Post processing :gear:

#577 Use more ClimaCore operators
  integration_tests/utils/main.jl
  integration_tests/utils/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
Labels: Performance :rocket:, Refactor :gear:

#588 update bc for precip, fix diagnostics
  integration_tests/utils/mse_tables.jl
  src/EDMF_Precipitation.jl
  src/diagnostics.jl
Labels: Microphysics :cloud_with_snow:

#583 Use ClimaCore operators
  integration_tests/utils/main.jl
  integration_tests/utils/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#590 Remove unused downwind operators
  src/Operators.jl
Labels: house cleaning :broom:

#593 Try to improve inference
  src/Turbulence_PrognosticTKE.jl
  src/update_aux.jl
Labels: Performance :rocket:, Naming conventions :capital_abcd:
