Repository CliMA/TurbulenceConvection.jl, pull requests merged in 2022-03, with the labels that each got.

#849 Change cluster data prefix
  perf/allocs.jl
  post_processing/compute_mse.jl
  utils/move_output.jl
Labels: Continuous Integration :gear:

#851 Hook regression tests back in
  post_processing/compute_mse.jl
Labels: Continuous Integration :gear:

#845 Unify driver files
  .buildkite/pipeline.yml
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/DYCOMS_RF02.jl
  integration_tests/DryBubble.jl
  integration_tests/GABLS.jl
  integration_tests/GATE_III.jl
  integration_tests/LES_driven_SCM.jl
  integration_tests/Rico.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/driver.jl
  integration_tests/life_cycle_Tan2018.jl
  post_processing/case_kwargs.jl
Labels: Refactor :gear:

#846 Fix readme
  README.md
Labels: documentation

#855 Check test, perf, and docs manifests into the repo
  .gitignore
  docs/Manifest.toml
  integration_tests/3dBomex.jl
  integration_tests/SP.jl
  integration_tests/baroclinic_wave.jl
  integration_tests/driver.jl
  perf/Manifest.toml
  perf/allocs.jl
  perf/common.jl
  perf/pgd.jl
  test/Manifest.toml
  test/runtests.jl
Labels: Continuous Integration :gear:

#854 Group pipeline steps
  .buildkite/pipeline.yml
Labels: Workflow :gear: :ocean:, Continuous Integration :gear:

#853 Add ODE+SDE back into alloc monitor
  perf/allocs.jl
Labels: Continuous Integration :gear:

#856 Make interactive easier to adjust default case
  README.md
  integration_tests/driver.jl
Labels: Workflow :gear: :ocean:

#857 Remove SP integration test file, add kwargs to case_kwargs
  integration_tests/SP.jl
  post_processing/case_kwargs.jl
Labels: house cleaning :broom:

#863 Fix environments - dev TC pkg in environments
  docs/Manifest.toml
  perf/Manifest.toml
  test/Manifest.toml
Labels: bugfix

#864 Move test env to integration_tests, add test/Project.toml
  .buildkite/pipeline.yml
  README.md
  integration_tests/Manifest.toml
  integration_tests/Project.toml
  perf/allocs.jl
Labels: Environments :mountain:

#858 Expand tests
  .buildkite/pipeline.yml
  integration_tests/driver.jl
  post_processing/post_run_tests.jl
Labels: Tests :warning:

#866 Fix scope of calibrate_io, add more fields
  driver/callbacks.jl
  driver/compute_diagnostics.jl
  driver/main.jl
  src/diagnostics.jl
Labels: calibration :dart:

#872 Fix up_deps script
  .dev/up_deps.jl
Labels: Workflow :gear: :ocean:

#873 Up manifests
  docs/Manifest.toml
  integration_tests/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#875 Move mse code loading to after solve, add prefixes for each job
  integration_tests/driver.jl
  perf/alloc_per_case.jl
  perf/benchmark.jl
  perf/benchmark_step.jl
  perf/inference_triggers.jl
  perf/invalidations.jl
  post_processing/case_kwargs.jl
Labels: bugfix, Race condition :runner:

#876 Make artifacts download lazily
  .buildkite/pipeline.yml
  integration_tests/artifact_funcs.jl
  integration_tests/download_artifacts.jl
Labels: bugfix, Continuous Integration :gear:

#883 Add flame graph script for io
  perf/flame_io.jl
Labels: Performance monitoring :rocket: :computer:

#878 Up deps
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  integration_tests/Manifest.toml
  integration_tests/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  test/Project.toml
Labels: Dependencies :spider_web:

#884 Upgrade to new version of NCDatasets
  docs/Manifest.toml
  integration_tests/Manifest.toml
  integration_tests/Project.toml
  test/Project.toml
Labels: Dependencies :spider_web:

#886 Check in artifacts toml
  integration_tests/Artifacts.toml
Labels: Continuous Integration :gear:

#887 Further refactor io
  docs/src/PlotReferenceStates.jl
  driver/NetCDFIO.jl
  driver/compute_diagnostics.jl
  driver/main.jl
Labels: Refactor :gear:

#888 Remove Stats in plotting ref profiles for docs
  docs/src/PlotReferenceStates.jl
Labels: Refactor :gear:

#889 Refactor IO
  driver/NetCDFIO.jl
  driver/compute_diagnostics.jl
  driver/main.jl
  src/diagnostics.jl
Labels: Refactor :gear:

#890 Add single value per column fields
  driver/compute_diagnostics.jl
  driver/dycore.jl
  driver/main.jl
  src/Grid.jl
  src/dycore_api.jl
  src/variables.jl
Labels: Refactor :gear:, IO :floppy_disk:

#893 Up dependencies
  docs/Manifest.toml
  integration_tests/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#896 Update artifacts toml, add cleanup to driver
  integration_tests/Artifacts.toml
  integration_tests/driver.jl
Labels: house cleaning :broom:

#904 Temporary fix for CI
  driver/main.jl
  integration_tests/Manifest.toml
  integration_tests/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  test/Project.toml
Labels: Continuous Integration :gear:

#902 add microphysics params for calibration
  driver/generate_namelist.jl
  driver/parameter_set.jl
  src/EDMF_Precipitation.jl
Labels: Microphysics :cloud_with_snow:

#672 Try stretched grids
  .buildkite/pipeline.yml
  driver/generate_namelist.jl
  driver/main.jl
  integration_tests/driver.jl
  src/Grid.jl
Labels: enhancement

#899 separate weights and biases
  driver/generate_namelist.jl
  driver/parameter_set.jl
  src/ClimaParams.jl
  src/closures/nondimensional_exchange_functions.jl
  src/types.jl
Labels: enhancement
