Repository CliMA/TurbulenceConvection.jl, pull requests merged in 2022-05, with the labels that each got.

#961 Compartmentalize grid construction into standalone function.
  driver/main.jl
Labels: Refactor :gear:

#965 Upgrade to latest JuliaFormatter
  .dev/Project.toml
  driver/main.jl
  integration_tests/3dBomex.jl
  integration_tests/baroclinic_wave.jl
  perf/allocs.jl
  src/EDMF_Updrafts.jl
  src/closures/nondimensional_exchange_functions.jl
  src/variables.jl
Labels: Dependencies :spider_web:

#973 Remove Pkg.develop in build
  .buildkite/pipeline.yml
Labels: Environments :mountain:

#975 Truncate printing of ClimaCore field types
  integration_tests/cli_options.jl
  integration_tests/driver.jl
  integration_tests/truncate_stack_traces.jl
Labels: Logging :ledger:

#978 Add error checking to CL overwrites
  integration_tests/driver.jl
  src/EDMF_functions.jl
  src/types.jl
  src/variables.jl
Labels: Defensive programming :crossed_swords:

#983 Upgrade deps
  docs/Manifest.toml
  integration_tests/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#981 Remove grid from surface_params
  Project.toml
  driver/Cases.jl
  driver/main.jl
  integration_tests/3dBomex.jl
  integration_tests/Project.toml
  integration_tests/baroclinic_wave.jl
  perf/Project.toml
  perf/invalidations.jl
  test/Project.toml
Labels: Refactor :gear:

#984 Remove zc_surf from surface_params arg list
  driver/Cases.jl
  driver/Surface.jl
  driver/main.jl
  integration_tests/3dBomex.jl
  integration_tests/baroclinic_wave.jl
Labels: Refactor :gear:, Dycore integration :earth_asia:

#989 Bump version
  Project.toml
Labels: Release

#1005 Verbose stack traces by default
  driver/generate_namelist.jl
  driver/main.jl
  integration_tests/cli_options.jl
  integration_tests/driver.jl
  integration_tests/trunc_field_type_print.jl
Labels: Logging :ledger:

#1000 Add internal clima parameters
  docs/src/API.md
  src/EDMF_Precipitation.jl
  src/EDMF_functions.jl
  src/ExperimentalClimaParams.jl
  src/InternalClimaParams.jl
  src/TurbulenceConvection.jl
  src/closures/buoyancy_gradients.jl
  src/closures/entr_detr.jl
  src/closures/mixing_length.jl
  src/closures/nondimensional_exchange_functions.jl
  src/closures/perturbation_pressure.jl
  src/microphysics_coupling.jl
  src/turbulence_functions.jl
  src/update_aux.jl
Labels: ClimaParameters :control_knobs:

#1010 fix cutoff precipitation
  .buildkite/pipeline.yml
  driver/compute_diagnostics.jl
  driver/generate_namelist.jl
  driver/main.jl
  integration_tests/3dBomex.jl
  integration_tests/baroclinic_wave.jl
  integration_tests/cli_options.jl
  integration_tests/driver.jl
  src/microphysics_coupling.jl
  src/types.jl
Labels: bugfix, Microphysics :cloud_with_snow:

#1017 Use Covariant3Vector for grid-mean w
  driver/dycore.jl
  src/Fields.jl
  src/TurbulenceConvection.jl
Labels: Dycore integration :earth_asia:

#1019 Remove baro wave example
  .buildkite/pipeline.yml
  integration_tests/baroclinic_wave.jl
Labels: house cleaning :broom:

#1020 Bump version number
  Project.toml
Labels: Release

#1026 Move prog init from Cases to dycore func
  driver/Cases.jl
  driver/dycore.jl
  driver/main.jl
Labels: Refactor :gear:

#1024 edit homepage and ref
  docs/bibliography.bib
  docs/src/index.md
Labels: documentation

#1031 Add energy variable type to dispatch on
  driver/dycore.jl
  driver/generate_namelist.jl
  driver/main.jl
  integration_tests/cli_options.jl
  integration_tests/driver.jl
  src/types.jl
Labels: enhancement

#1023 Add prescribed and diagnostic precip fraction
  .buildkite/pipeline.yml
  driver/generate_namelist.jl
  driver/parameter_set.jl
  integration_tests/cli_options.jl
  integration_tests/driver.jl
  src/EDMF_Environment.jl
  src/EDMF_Precipitation.jl
  src/EDMF_Updrafts.jl
  src/ExperimentalClimaParams.jl
  src/microphysics_coupling.jl
  src/types.jl
  src/update_aux.jl
Labels: Microphysics :cloud_with_snow:

#1001 update to CloudMicrophysics v0.5.0
  Project.toml
  docs/Manifest.toml
  driver/main.jl
  integration_tests/Manifest.toml
  integration_tests/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  src/TurbulenceConvection.jl
  src/microphysics_coupling.jl
  src/update_aux.jl
  test/Project.toml
Labels: Microphysics :cloud_with_snow:

#1033 Bump version
  Project.toml
Labels: Release

#1042 Bump version for new release
  Project.toml
Labels: Release

#1038 Use Covariant12Vector for horiz vel
  driver/Cases.jl
  driver/Radiation.jl
  driver/Surface.jl
  driver/callbacks.jl
  driver/dycore.jl
  src/EDMF_functions.jl
  src/diagnostics.jl
  src/dycore_api.jl
  src/turbulence_functions.jl
  src/update_aux.jl
Labels: Dycore integration :earth_asia:

#1045 Test that CI does not crash for non-vanilla cases
  .buildkite/pipeline.yml
  Project.toml
  driver/callbacks.jl
  driver/compute_diagnostics.jl
  driver/main.jl
  integration_tests/cli_options.jl
  integration_tests/driver.jl
  src/diagnostics.jl
Labels: Tests :warning:, Continuous Integration :gear:

#1056 Fix non-equilibroum buoyancy calculations
  src/update_aux.jl
Labels: bugfix, Microphysics :cloud_with_snow:

#1059 Construct grid with spaces
  src/Grid.jl
  test/clima_core_extensions.jl
Labels: Dycore integration :earth_asia:

#1060 Remove some ClimaCore hacks
  docs/src/PlotReferenceStates.jl
  driver/Cases.jl
  driver/NetCDFIO.jl
  driver/Radiation.jl
  driver/Surface.jl
  driver/dycore.jl
  driver/initial_conditions.jl
  post_processing/mse_tables.jl
  src/EDMF_functions.jl
  src/Grid.jl
  src/turbulence_functions.jl
Labels: Dycore integration :earth_asia:

#1057 fix buoyancy calculations for non-equilibrium moisture model
  post_processing/mse_tables.jl
  src/update_aux.jl
Labels: bugfix, Microphysics :cloud_with_snow:

#1067 Update dependencies
  Project.toml
  docs/Manifest.toml
  integration_tests/Manifest.toml
  integration_tests/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  test/Project.toml
Labels: Dependencies :spider_web:

#1064 fixes in microphysics source terms to e_tot
  .buildkite/pipeline.yml
  post_processing/mse_tables.jl
  src/EDMF_Precipitation.jl
  src/microphysics_coupling.jl
  utils/print_new_mse.jl
Labels: Microphysics :cloud_with_snow:

#1068 Update some deps
  Project.toml
  docs/Manifest.toml
  integration_tests/Manifest.toml
  integration_tests/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  test/Project.toml
Labels: Dependencies :spider_web:

#1070 Remove 3D box example
  .buildkite/pipeline.yml
  integration_tests/3dBomex.jl
Labels: house cleaning :broom:

#1071 Remove unused function
  driver/Cases.jl
Labels: house cleaning :broom:

#1072 Internalize and unify all climaparameters
  docs/src/API.md
  driver/Cases.jl
  driver/Radiation.jl
  driver/dycore.jl
  src/EDMF_Precipitation.jl
  src/EDMF_functions.jl
  src/ExperimentalClimaParams.jl
  src/TurbulenceConvection.jl
  src/TurbulenceConvectionParameters.jl
  src/closures/buoyancy_gradients.jl
  src/closures/entr_detr.jl
  src/closures/mixing_length.jl
  src/closures/nondimensional_exchange_functions.jl
  src/closures/perturbation_pressure.jl
  src/microphysics_coupling.jl
  src/thermodynamics.jl
  src/turbulence_functions.jl
  src/update_aux.jl
Labels: ClimaParameters :control_knobs:, Breaking changes :boom:

#1075 Refactor init profiles in LES driven SCM
  driver/Cases.jl
Labels: Refactor :gear:, Dycore integration :earth_asia:

#1076 Make RF broken test true
  .buildkite/pipeline.yml
Labels: Tests :warning:

#1077 Prep for sphere
  driver/NetCDFIO.jl
  driver/main.jl
  integration_tests/cli_options.jl
  integration_tests/driver.jl
  src/Fields.jl
  src/Grid.jl
  src/types.jl
Labels: Refactor :gear:

#1079 Compute column grid on the fly from state space
  driver/callbacks.jl
  driver/dycore.jl
  driver/main.jl
  perf/common.jl
  perf/jet.jl
Labels: Refactor :gear:, Dycore integration :earth_asia:

#1080 Remove state from Simulation1D
  driver/main.jl
  perf/common.jl
  perf/jet.jl
Labels: Refactor :gear:, Dycore integration :earth_asia:

#1078 Move some experimental clima parameters into structs
  driver/parameter_set.jl
  src/EDMF_Environment.jl
  src/EDMF_Precipitation.jl
  src/EDMF_Updrafts.jl
  src/TurbulenceConvectionParameters.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:, ClimaParameters :control_knobs:

#1082 Prep for sphere
  driver/callbacks.jl
  driver/common_spaces.jl
  driver/dycore.jl
  driver/main.jl
  src/types.jl
Labels: Refactor :gear:, Dycore integration :earth_asia:

#1084 Generalize some driver init and forcing for LES driven SCM
  driver/Cases.jl
  driver/Forcing.jl
  driver/Radiation.jl
Labels: Refactor :gear:, Dycore integration :earth_asia:

#1074 Prep to generalize host model for a sphere
  driver/callbacks.jl
  driver/common_spaces.jl
  driver/dycore.jl
  driver/main.jl
  perf/inference_triggers.jl
  post_processing/mse_tables.jl
  src/Grid.jl
Labels: Dycore integration :earth_asia:
