Repository CliMA/TurbulenceConvection.jl, pull requests merged in 2022-04, with the labels that each got.

#909 Monitor dependencies are updated
  .github/workflows/UpDeps.yml
  docs/Manifest.toml
  integration_tests/Manifest.toml
  perf/Manifest.toml
Labels: Continuous Integration :gear:

#913 Replace invalidations plot with table
  perf/invalidations.jl
Labels: Performance monitoring :rocket: :computer:

#915 Bump version for new release
  Project.toml
Labels: Release

#916 Add column_state helper func
  Project.toml
  integration_tests/3dBomex.jl
  src/types.jl
Labels: Refactor :gear:

#912 Add truncated GATE to CI
  .buildkite/pipeline.yml
  driver/Cases.jl
  integration_tests/driver.jl
  post_processing/case_kwargs.jl
  post_processing/compute_mse.jl
  post_processing/mse_tables.jl
  utils/print_new_mse.jl
Labels: Tests :warning:

#919 Try to fix CI
  post_processing/mse_tables.jl
Labels: Continuous Integration :gear:

#925 Add and update some docs and doc stubs
  README.md
  docs/make.jl
  docs/src/API.md
  docs/src/Formulation.md
  docs/src/PlotReferenceStates.jl
  docs/src/ReferenceStates.md
  docs/src/dev.md
  docs/src/index.md
Labels: documentation

#927 Up deps, bump version
  Project.toml
  docs/Manifest.toml
  integration_tests/Manifest.toml
  integration_tests/Project.toml
  perf/Manifest.toml
  test/Project.toml
Labels: Release

#932 Refactor cli options
  .buildkite/pipeline.yml
  driver/NetCDFIO.jl
  integration_tests/cli_options.jl
  integration_tests/driver.jl
Labels: Refactor :gear:

#929 Add multiple updraft buildkite job
  .buildkite/pipeline.yml
  integration_tests/cli_options.jl
  integration_tests/driver.jl
Labels: bugfix, Continuous Integration :gear:

#935 Upgrade to latest (breaking version of) Thermodynamics
  Project.toml
  docs/Manifest.toml
  driver/Cases.jl
  driver/Surface.jl
  driver/compute_diagnostics.jl
  driver/dycore.jl
  driver/initial_conditions.jl
  integration_tests/Manifest.toml
  integration_tests/Project.toml
  perf/Manifest.toml
  post_processing/mse_tables.jl
  src/EDMF_Environment.jl
  src/EDMF_Precipitation.jl
  src/closures/buoyancy_gradients.jl
  src/microphysics_coupling.jl
  src/update_aux.jl
  test/Project.toml
Labels: Dependencies :spider_web:

#938 bump version for new release
  Project.toml
Labels: Release

#940 Add to the cli options, unify env_buoy_grad and sgs
  .buildkite/pipeline.yml
  driver/generate_namelist.jl
  integration_tests/cli_options.jl
  integration_tests/driver.jl
  src/types.jl
Labels: Continuous Integration :gear:, Consistency :dart:

#941 Add RRTMGP.jl dependency (+ up deps)
  docs/Manifest.toml
  integration_tests/Manifest.toml
  integration_tests/Project.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#928 Optional non-equilibrium moisture model
  .buildkite/pipeline.yml
  driver/Surface.jl
  driver/compute_diagnostics.jl
  driver/dycore.jl
  driver/generate_namelist.jl
  driver/initial_conditions.jl
  integration_tests/cli_options.jl
  src/EDMF_Environment.jl
  src/EDMF_Precipitation.jl
  src/EDMF_Updrafts.jl
  src/EDMF_functions.jl
  src/microphysics_coupling.jl
  src/thermodynamics.jl
  src/types.jl
  src/update_aux.jl
  src/variables.jl
Labels: Microphysics :cloud_with_snow:

#945 Add thermo state fields, use in one place
  driver/Cases.jl
  driver/dycore.jl
  src/variables.jl
Labels: Refactor :gear:

#948 Add backticks to info statements
  integration_tests/download_artifacts.jl
  perf/alloc_per_case.jl
  perf/alloc_per_case_with_init_io.jl
  perf/common.jl
  post_processing/compute_mse.jl
  src/TurbulenceConvection.jl
  utils/move_output.jl
Labels: Logging :ledger:

#949 Warn when overwriting namelist
  integration_tests/driver.jl
Labels: Logging :ledger:

#947 Use thermo state field cache more
  driver/Cases.jl
  driver/compute_diagnostics.jl
  driver/dycore.jl
  post_processing/mse_tables.jl
  src/EDMF_Environment.jl
  src/update_aux.jl
Labels: Thermodynamics :fire:

#953 Prep for variable type and name change
  driver/dycore.jl
  driver/main.jl
  integration_tests/3dBomex.jl
  integration_tests/baroclinic_wave.jl
  src/Fields.jl
  src/types.jl
  src/variables.jl
Labels: Refactor :gear:

#954 Use more cached thermo state fields
  post_processing/mse_tables.jl
  src/EDMF_Precipitation.jl
Labels: Refactor :gear:, Thermodynamics :fire:

#959 Enforce definition of nz or dz in LESdrivenSCM, not both.
  docs/Manifest.toml
  driver/generate_namelist.jl
  driver/main.jl
  integration_tests/Manifest.toml
  perf/Manifest.toml
  post_processing/mse_tables.jl
Labels: Consistency :dart:
