Repository CliMA/TurbulenceConvection.jl, pull requests merged in 2022-02, with the labels that each got.

#782 Update readme
  README.md
Labels: documentation

#785 rename compute_sgs_tendencies to compute_sgs_flux
  driver/dycore.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:, Naming conventions :capital_abcd:

#786 remove unused inputs
  driver/dycore.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#787 Make environments more user-friendly
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/DYCOMS_RF02.jl
  integration_tests/DryBubble.jl
  integration_tests/GABLS.jl
  integration_tests/GATE_III.jl
  integration_tests/LES_driven_SCM.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/SP.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/life_cycle_Tan2018.jl
  perf/allocs.jl
  perf/common.jl
  perf/invalidations.jl
  perf/pgd.jl
  test/Project.toml
  test/runtests.jl
Labels: Refactor :gear:

#789 Bump version
  Project.toml
Labels: Release

#791 Improve names
  driver/compute_diagnostics.jl
  driver/dycore.jl
  driver/initial_conditions.jl
  driver/main.jl
  src/EDMF_Precipitation.jl
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
  src/closures/entr_detr.jl
  src/closures/perturbation_pressure.jl
  src/types.jl
  src/update_aux.jl
Labels: Naming conventions :capital_abcd:

#797 Let CI pass
  post_processing/compute_mse.jl
  utils/move_output.jl
Labels: Continuous Integration :gear:

#798 Revert PR 797 to reinforce regression tests
  post_processing/compute_mse.jl
Labels: Continuous Integration :gear:

#803 Reduce use of GridMeanVariables in TC
  driver/Surface.jl
  driver/callbacks.jl
  driver/compute_diagnostics.jl
  driver/dycore.jl
  driver/initial_conditions.jl
  driver/main.jl
  src/EDMF_Precipitation.jl
  src/EDMF_functions.jl
  src/update_aux.jl
Labels: Refactor :gear:

#804 Remove GridMeanVariables
  driver/Cases.jl
  driver/Radiation.jl
  driver/callbacks.jl
  driver/compute_diagnostics.jl
  driver/dycore.jl
  driver/main.jl
  perf/common.jl
  perf/jet.jl
  src/EDMF_functions.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#802 Use AtmosphericProfilesLibrary.jl
  docs/Project.toml
  driver/Cases.jl
  driver/initial_conditions.jl
  perf/Project.toml
  test/Project.toml
Labels: Refactor :gear:

#805 Fuse some TC tendency functions
  driver/dycore.jl
  src/EDMF_functions.jl
  src/update_aux.jl
Labels: Refactor :gear:

#806 Make reference_params return a thermo state
  docs/src/PlotReferenceStates.jl
  driver/Cases.jl
  driver/dycore.jl
  driver/main.jl
Labels: Refactor :gear:

#809 Unfuse some TC tendency functions
  driver/dycore.jl
  src/EDMF_functions.jl
Labels: Refactor :gear:

#810 Add 3d sphere baroclinic wave example
  .buildkite/pipeline.yml
  integration_tests/baroclinic_wave.jl
  test/Project.toml
Labels: Tests :warning:

#818 Remove ClimaCorePlots to allow ClimaCore update
  integration_tests/baroclinic_wave.jl
  test/Project.toml
Labels: Dependencies :spider_web:

#817 Add compare debug function
  src/utility_functions.jl
Labels: Debugging :bug: :hammer:

#820 Make model variables depend on the model
  driver/dycore.jl
  driver/main.jl
  integration_tests/3dBomex.jl
  integration_tests/baroclinic_wave.jl
  src/types.jl
  src/variables.jl
Labels: Refactor :gear:

#822 Bump version
  Project.toml
Labels: Release

#828 Improve logging, remove ref to undefined var
  driver/Cases.jl
  driver/dycore.jl
Labels: bugfix

#829 Propagate kwarg in main1d
  driver/main.jl
Labels: bugfix

#832 Change println to at-info
  driver/main.jl
Labels: Logging :ledger:

#836 Add calibrate_io namelist bool
  driver/generate_namelist.jl
  driver/main.jl
  src/diagnostics.jl
Labels: calibration :dart:

#835 Ensure NC files always close
  driver/main.jl
Labels: IO :floppy_disk:

#839 Bump version
  Project.toml
Labels: Release

#840 Make benchmark more precise, remove update_n
  perf/alloc_per_case.jl
  perf/benchmark.jl
  perf/common.jl
  perf/profile.jl
Labels: Performance monitoring :rocket: :computer:

#841 Include exception error in log for crashed simulations
  Project.toml
  driver/main.jl
Labels: Logging :ledger:
