Repository CliMA/TurbulenceConvection.jl, pull requests merged in 2022-01, with the labels that each got.

#700 Add/use immutable surface types
  driver/Cases.jl
  src/Surface.jl
  src/types.jl
Labels: Refactor :gear:

#701 Improve some names
  driver/Cases.jl
  src/Surface.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
Labels: Naming conventions :capital_abcd:

#703 Make `SurfaceBase` immutable
  driver/Cases.jl
  driver/callbacks.jl
  driver/initial_conditions.jl
  driver/main.jl
  post_processing/mse_tables.jl
  src/Surface.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
  src/update_aux.jl
Labels: Improved pattern :building_construction:

#682 Make sde closure immutable
  src/stochastic_closures.jl
  src/types.jl
Labels: Refactor :gear:

#705 Make CasesBase immutable
  driver/Cases.jl
  post_processing/mse_tables.jl
  src/types.jl
Labels: Improved pattern :building_construction:

#707 Make inversion_option a type
  driver/Cases.jl
  driver/main.jl
  src/types.jl
Labels: Refactor :gear:

#709 Add precompilable scripts
  .buildkite/pipeline.yml
  perf/benchmark.jl
  perf/common.jl
  perf/precompilable.jl
  perf/precompilable_no_init.jl
  perf/precompilable_no_init_io.jl
  perf/precompilable_no_io.jl
Labels: Performance monitoring :rocket: :computer:

#712 Add script for profile-guided despecialization
  perf/pgd.jl
Labels: Performance monitoring :rocket: :computer:

#713 Misc cleanup
  driver/Cases.jl
  driver/TimeStepping.jl
  driver/callbacks.jl
  driver/compute_diagnostics.jl
  driver/main.jl
  src/EDMF_Environment.jl
  src/EDMF_Precipitation.jl
  src/ReferenceState.jl
  src/Surface.jl
  src/TimeStepping.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/io.jl
  src/microphysics_coupling.jl
  src/parameters.jl
  src/types.jl
Labels: house cleaning :broom:

#633 Add exhaustive allocation tracking job
  .buildkite/pipeline.yml
  perf/alloc_per_case_with_init_io.jl
  perf/allocs.jl
  perf/common.jl
Labels: Performance monitoring :rocket: :computer:

#716 Move updraft_top comp to before its used
  post_processing/mse_tables.jl
  src/update_aux.jl
Labels: bugfix

#715 Compute updraft_top on-the-fly
  src/Grid.jl
  src/Turbulence_PrognosticTKE.jl
  src/closures/perturbation_pressure.jl
  src/turbulence_functions.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#717 Compute `pressure_plume_spacing` on the fly
  driver/compute_diagnostics.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#718 Cleanup unused updraft variables
  driver/compute_diagnostics.jl
  driver/initial_conditions.jl
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
  src/update_aux.jl
Labels: house cleaning :broom:

#719 Compute BCs on the fly
  driver/callbacks.jl
  driver/compute_diagnostics.jl
  driver/initial_conditions.jl
  driver/main.jl
  post_processing/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
  src/io.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#721 Misc cleanup
  src/EDMF_Updrafts.jl
  src/Turbulence_PrognosticTKE.jl
  src/microphysics_coupling.jl
  src/turbulence_functions.jl
  src/types.jl
Labels: house cleaning :broom:

#724 Hoist code, decompose expressions
  perf/inference_triggers.jl
  post_processing/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#722 Move some pieces outside of src
  Project.toml
  driver/Cases.jl
  driver/Surface.jl
  driver/callbacks.jl
  driver/compute_diagnostics.jl
  driver/dycore.jl
  driver/initial_conditions.jl
  driver/main.jl
  perf/common.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#728 Remove closure over folder
  perf/allocs.jl
Labels: Refactor :gear:, Post processing :gear:

#725 Move some code outside of src
  docs/Project.toml
  docs/src/PlotReferenceStates.jl
  driver/dycore.jl
  driver/main.jl
  src/ReferenceState.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
Labels: Refactor :gear:

#733 Move Radiation and Forcing to driver/
  driver/Cases.jl
  driver/Forcing.jl
  driver/Radiation.jl
  driver/dycore.jl
  driver/main.jl
  perf/common.jl
  post_processing/mse_tables.jl
  src/Forcing.jl
  src/TurbulenceConvection.jl
  src/Turbulence_PrognosticTKE.jl
  src/update_aux.jl
Labels: Refactor :gear:

#738 Move `NetCDFIO_Stats` outside of src
  Project.toml
  docs/Project.toml
  docs/bibliography.bib
  docs/src/PlotReferenceStates.jl
  driver/Cases.jl
  driver/NetCDFIO.jl
  driver/callbacks.jl
  driver/compute_diagnostics.jl
  driver/main.jl
  perf/common.jl
  perf/cthulhu.jl
  perf/flame.jl
  perf/inference_triggers.jl
  perf/precompilable_no_init.jl
  src/TurbulenceConvection.jl
  src/diagnostics.jl
  src/io.jl
Labels: Refactor :gear:

#739 Remove some unused deps
  Project.toml
  src/TurbulenceConvection.jl
Labels: Dependencies :spider_web:

#747 Use Pkg.develop instead of LOAD_PATH
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/DryBubble.jl
  integration_tests/GABLS.jl
  integration_tests/GATE_III.jl
  integration_tests/LES_driven_SCM.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/SP.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/life_cycle_Tan2018.jl
  test/runtests.jl
Labels: Workflow :gear: :ocean:

#745 Reduce allocations
  src/Turbulence_PrognosticTKE.jl
  src/closures/perturbation_pressure.jl
  src/update_aux.jl
Labels: Performance :rocket:, Refactor :gear:

#746 Add DYCOMS_RF02 case
  .buildkite/pipeline.yml
  docs/bibliography.bib
  driver/Cases.jl
  driver/generate_namelist.jl
  integration_tests/DYCOMS_RF02.jl
  post_processing/Artifacts.toml
  post_processing/compute_mse.jl
  post_processing/mse_tables.jl
  utils/print_new_mse.jl
Labels: Tests :warning:, Microphysics :cloud_with_snow:

#750 Fix GHA CI
  test/runtests.jl
Labels: Continuous Integration :gear:

#749 Allow for non-local entr-detr models
  src/closures/entr_detr.jl
  src/types.jl
  src/update_aux.jl
  src/variables.jl
Labels: Refactor :gear:

#759 Add JET script, fix some runtime dispatch
  driver/Surface.jl
  perf/jet.jl
  src/Operators.jl
  src/update_aux.jl
  src/utility_functions.jl
Labels: Refactor :gear:

#760 Add runtime flame graph script
  perf/Project.toml
  perf/flame.jl
  perf/inference_flame.jl
Labels: Performance monitoring :rocket: :computer:

#761 Use PProf in flame graph
  .gitignore
  perf/Project.toml
  perf/flame.jl
Labels: Performance monitoring :rocket: :computer:

#763 SGS flux bug fixes
  post_processing/mse_tables.jl
  src/Turbulence_PrognosticTKE.jl
Labels: bugfix

#767 Widen allocation monitoring
  driver/main.jl
  perf/flame.jl
  perf/precompilable_no_init.jl
  perf/precompilable_no_init_io.jl
Labels: Performance monitoring :rocket: :computer:

#769 Remove allocation
  src/Turbulence_PrognosticTKE.jl
Labels: Performance :rocket:

#768 Prep for ClimaCore update, fixup flame script
  perf/common.jl
  perf/flame.jl
  test/Project.toml
Labels: Refactor :gear:

#772 Use pkgdir
  docs/src/PlotReferenceStates.jl
  driver/main.jl
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/DYCOMS_RF02.jl
  integration_tests/DryBubble.jl
  integration_tests/GABLS.jl
  integration_tests/GATE_III.jl
  integration_tests/LES_driven_SCM.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/SP.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/life_cycle_Tan2018.jl
  perf/common.jl
  perf/cthulhu.jl
  perf/inference_flame.jl
  perf/inference_triggers.jl
  perf/invalidations.jl
  perf/pgd.jl
  perf/precompilable.jl
  perf/precompilable_no_init.jl
  perf/precompilable_no_init_io.jl
  perf/precompilable_no_io.jl
Labels: Refactor :gear:

#773 Dev only when necessary, improve code loading
  .buildkite/pipeline.yml
  integration_tests/ARM_SGP.jl
  integration_tests/Bomex.jl
  integration_tests/DYCOMS_RF01.jl
  integration_tests/DYCOMS_RF02.jl
  integration_tests/DryBubble.jl
  integration_tests/GABLS.jl
  integration_tests/GATE_III.jl
  integration_tests/LES_driven_SCM.jl
  integration_tests/Nieuwstadt.jl
  integration_tests/Rico.jl
  integration_tests/SP.jl
  integration_tests/Soares.jl
  integration_tests/TRMM_LBA.jl
  integration_tests/life_cycle_Tan2018.jl
  perf/alloc_per_case.jl
  perf/alloc_per_case_with_init_io.jl
  perf/allocs.jl
  perf/benchmark.jl
  perf/common.jl
  perf/cthulhu.jl
  perf/flame.jl
  perf/inference_flame.jl
  perf/inference_triggers.jl
  perf/jet.jl
  perf/pgd.jl
  perf/precompilable.jl
  perf/precompilable_no_init.jl
  perf/precompilable_no_init_io.jl
  perf/precompilable_no_io.jl
  perf/profile.jl
Labels: Refactor :gear:

#770 Update to latest ClimaCore
  Project.toml
  src/Fields.jl
  test/Project.toml
Labels: Dependencies :spider_web:

#774 Add perf benchmark for ODE.step
  .buildkite/pipeline.yml
  perf/benchmark_step.jl
Labels: Performance monitoring :rocket: :computer:
