Repository CliMA/TurbulenceConvection.jl, pull requests merged in 2022-06, with the labels that each got.

#1083 Limit benchmark samples
  perf/benchmark.jl
  perf/benchmark_step.jl
Labels: Performance monitoring :mag::rocket:

#1090 Prep for sphere
  .buildkite/pipeline.yml
  driver/common_spaces.jl
  driver/main.jl
  perf/cthulhu.jl
  perf/flame_io.jl
  perf/inference_flame.jl
  perf/inference_triggers.jl
  perf/precompilable_no_init.jl
  src/Fields.jl
Labels: Refactor :gear:, Dycore integration :earth_asia:

#1089 Conditionally compute parsed args
  integration_tests/driver.jl
Labels: Workflow :gear: :ocean:

#1085 Add test edmf sphere test
  .buildkite/pipeline.yml
  driver/callbacks.jl
  driver/main.jl
  integration_tests/driver.jl
  integration_tests/sphere_utils.jl
  perf/inference_flame.jl
  perf/invalidations.jl
  perf/pgd.jl
  src/Fields.jl
  src/Grid.jl
  src/types.jl
  test/runtests.jl
Labels: Tests :warning:, Dycore integration :earth_asia:

#1097 Add set_src_seed option for identical column test
  .buildkite/pipeline.yml
  Project.toml
  driver/generate_namelist.jl
  integration_tests/cli_options.jl
  integration_tests/driver.jl
  src/EDMF_functions.jl
  src/TurbulenceConvection.jl
  src/types.jl
  src/utility_functions.jl
Labels: Tests :warning:, Refactor :gear:, Dycore integration :earth_asia:

#1098 Remove overloading +- for Covariant3Vectors
  driver/dycore.jl
  src/EDMF_functions.jl
  src/Fields.jl
  src/closures/entr_detr.jl
Labels: Defensive programming :crossed_swords:

#1100 Use norm_sqr for kinetic energy
  driver/dycore.jl
  post_processing/mse_tables.jl
  src/dycore_api.jl
  src/update_aux.jl
Labels: Refactor :gear:

#1103 Fix some type instabilities, make code more type-generic
  driver/NetCDFIO.jl
  driver/TimeStepping.jl
  driver/compute_diagnostics.jl
  driver/main.jl
  integration_tests/Manifest.toml
Labels: Refactor :gear:

#1107 Fix more type instabilities
  src/EDMF_functions.jl
Labels: Refactor :gear:

#1109 Move experimental parameters to struct
  driver/parameter_set.jl
  src/EDMF_functions.jl
  src/TurbulenceConvectionParameters.jl
  src/types.jl
Labels: ClimaParameters :control_knobs:

#1111 Move experimental params into struct
  driver/parameter_set.jl
  src/TurbulenceConvectionParameters.jl
  src/closures/nondimensional_exchange_functions.jl
  src/types.jl
Labels: Refactor :gear:, ClimaParameters :control_knobs:

#1112 Move more parameters to structs
  driver/parameter_set.jl
  src/TurbulenceConvectionParameters.jl
  src/closures/nondimensional_exchange_functions.jl
  src/types.jl
Labels: Refactor :gear:, ClimaParameters :control_knobs:

#1114 Fix/cleanup some diagnostics
  driver/compute_diagnostics.jl
Labels: house cleaning :broom:, Refactor :gear:

#1113 Move more parameters to structs
  driver/parameter_set.jl
  src/TurbulenceConvectionParameters.jl
  src/closures/nondimensional_exchange_functions.jl
  src/types.jl
Labels: Refactor :gear:, ClimaParameters :control_knobs:

#1115 Wrap entr_pi_subset in Tuple in edmf constructor
  src/types.jl
Labels: Refactor :gear:

#1116 Move more parameters to edmf struct
  driver/parameter_set.jl
  src/TurbulenceConvectionParameters.jl
  src/closures/nondimensional_exchange_functions.jl
  src/types.jl
Labels: Refactor :gear:, ClimaParameters :control_knobs:

#1119 Bump precompilation time speedup test
  perf/precompilable_no_init.jl
Labels: Tests :warning:, Flakey tests

#1118 Remove unused parameter, move params to structs
  driver/parameter_set.jl
  src/EDMF_functions.jl
  src/TurbulenceConvectionParameters.jl
  src/closures/entr_detr.jl
  src/closures/nondimensional_exchange_functions.jl
  src/types.jl
Labels: Refactor :gear:, ClimaParameters :control_knobs:

#1121 Add printing of edmf model summary
  driver/main.jl
  src/types.jl
Labels: Logging :ledger:

#1117 Update deps
  docs/Manifest.toml
  integration_tests/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#1122 Fix buildkite job for Bomex with Gaussian
  .buildkite/pipeline.yml
Labels: bugfix

#1120 Move more parameters into structs
  driver/compute_diagnostics.jl
  driver/main.jl
  driver/parameter_set.jl
  src/EDMF_functions.jl
  src/TurbulenceConvectionParameters.jl
  src/closures/entr_detr.jl
  src/closures/nondimensional_exchange_functions.jl
  src/closures/perturbation_pressure.jl
  src/types.jl
Labels: Refactor :gear:, ClimaParameters :control_knobs:

#1124 Move more parameters into structs
  driver/parameter_set.jl
  src/EDMF_functions.jl
  src/TurbulenceConvectionParameters.jl
  src/closures/mixing_length.jl
  src/closures/perturbation_pressure.jl
  src/turbulence_functions.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:, ClimaParameters :control_knobs:

#1125 Bump minor version for new release
  Project.toml
Labels: Release

#1127 Alleviate dependence on CasesBase
  driver/Cases.jl
  driver/Forcing.jl
  driver/dycore.jl
  driver/initial_conditions.jl
  driver/main.jl
  src/types.jl
Labels: Refactor :gear:

#1136 Upgrade deps and julia to 1.7.3
  docs/Manifest.toml
  integration_tests/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#1133 Move TC-external types outside of source.
  driver/Cases.jl
  driver/Forcing.jl
  driver/Radiation.jl
  driver/dycore.jl
  driver/main.jl
  perf/Project.toml
  src/EDMF_functions.jl
  src/types.jl
Labels: Refactor :gear:

#1138 Move dycore variables into separate file
  driver/dycore.jl
  driver/dycore_variables.jl
Labels: Refactor :gear:

#1142 remove is surface in update_aux
  post_processing/mse_tables.jl
  src/update_aux.jl
Labels: house cleaning :broom:

#1141 Clean up unused functions
  src/thermodynamics.jl
Labels: house cleaning :broom:

#1144 Use cache over copy
  src/EDMF_functions.jl
  src/update_aux.jl
Labels: Refactor :gear:

#1153 Get FT from float_type (added)
  driver/Cases.jl
  driver/Radiation.jl
  driver/Surface.jl
  driver/compute_diagnostics.jl
  driver/dycore.jl
  driver/initial_conditions.jl
  driver/main.jl
  src/EDMF_Precipitation.jl
  src/EDMF_functions.jl
  src/closures/entr_detr.jl
  src/closures/perturbation_pressure.jl
  src/types.jl
  src/update_aux.jl
Labels: Refactor :gear:

#1154 Add/use thermo parameter wrapper
  driver/Cases.jl
  driver/Surface.jl
  driver/compute_diagnostics.jl
  driver/dycore.jl
  driver/initial_conditions.jl
  driver/parameter_set.jl
  src/EDMF_Environment.jl
  src/EDMF_Precipitation.jl
  src/EDMF_functions.jl
  src/TurbulenceConvection.jl
  src/closures/buoyancy_gradients.jl
  src/thermodynamics.jl
  src/update_aux.jl
Labels: Refactor :gear:, ClimaParameters :control_knobs:

#1155 Upgrade deps
  docs/Manifest.toml
  integration_tests/Manifest.toml
  perf/Manifest.toml
Labels: Dependencies :spider_web:

#1158 Add missed calls to thermo wrappers
  driver/Cases.jl
  src/EDMF_Updrafts.jl
  src/microphysics_coupling.jl
Labels: Refactor :gear:, Thermodynamics :fire:, ClimaParameters :control_knobs:

#1157 Add microphysics param wrappers
  driver/parameter_set.jl
  src/EDMF_Precipitation.jl
  src/TurbulenceConvection.jl
  src/microphysics_coupling.jl
  src/update_aux.jl
Labels: Refactor :gear:, ClimaParameters :control_knobs:, Microphysics :cloud_with_snow:

#1156 Add job to test using dual numbers
  .buildkite/pipeline.yml
  docs/src/PlotReferenceStates.jl
  driver/Cases.jl
  driver/dycore.jl
  driver/generate_namelist.jl
  driver/main.jl
  driver/parameter_set.jl
  integration_tests/Project.toml
  integration_tests/cli_options.jl
  integration_tests/driver.jl
  perf/Project.toml
  src/EDMF_Environment.jl
  src/EDMF_Updrafts.jl
  src/EDMF_functions.jl
  src/closures/entr_detr.jl
  src/thermodynamics.jl
  src/turbulence_functions.jl
  src/types.jl
  src/update_aux.jl
  test/Project.toml
Labels: enhancement, Tests :warning:

#1163 Add docs for CL arguments and run scripts
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/src/cl_args.jl
  docs/src/cl_args.md
  docs/src/repl_scripts.jl
  docs/src/repl_scripts.md
  integration_tests/cli_options.jl
Labels: documentation, Workflow :gear: :ocean:

#1164 Add / use surface fluxes parameters wrapper
  driver/Surface.jl
  driver/parameter_set.jl
  src/TurbulenceConvection.jl
Labels: Refactor :gear:, ClimaParameters :control_knobs:

#1165 Bump minor version
  Project.toml
Labels: Release

#1167 zero out tendecies before update_aux
  driver/dycore.jl
  post_processing/mse_tables.jl
Labels: bugfix

#1175 Split up print repl script
  integration_tests/cli_options.jl
Labels: Workflow :gear: :ocean:

#1173 Use correct ClimaCore types and operators for horizontal velocities
  driver/Cases.jl
  driver/Surface.jl
  driver/dycore.jl
  driver/dycore_variables.jl
  post_processing/mse_tables.jl
  src/EDMF_functions.jl
  src/Fields.jl
  src/TurbulenceConvection.jl
  src/diagnostics.jl
  src/dycore_api.jl
  src/turbulence_functions.jl
  src/update_aux.jl
  src/variables.jl
Labels: Dycore integration :earth_asia:

#1176 Move overwrite namelist into a separate function
  integration_tests/driver.jl
  integration_tests/overwrite_namelist.jl
Labels: Workflow :gear: :ocean:, Logging :ledger:

#1180 Fix subtype bug, remove unused method definition
  integration_tests/cli_options.jl
  src/Fields.jl
Labels: bugfix

#1179 Fix type instabilities
  driver/Cases.jl
  driver/main.jl
  src/types.jl
Labels: Refactor :gear:, Breaking changes :boom:, Type stability :surfer:

#1181 Reshape arrays at init, parameterize array dims
  src/closures/nondimensional_exchange_functions.jl
  src/types.jl
Labels: Refactor :gear:

#1182 Make parsed_args_from_cl_flags more flexible
  integration_tests/cli_options.jl
Labels: Refactor :gear:

#1184 Remove unused point space
  src/Grid.jl
Labels: house cleaning :broom:, Refactor :gear:

#1188 Bump version for new release
  Project.toml
Labels: Release

#1192 Upgrade to latest deps, use new clima parameter handling
  .buildkite/pipeline.yml
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  docs/src/API.md
  docs/src/PlotReferenceStates.jl
  driver/Cases.jl
  driver/Surface.jl
  driver/common_spaces.jl
  driver/compute_diagnostics.jl
  driver/dycore.jl
  driver/dycore_variables.jl
  driver/initial_conditions.jl
  driver/main.jl
  driver/parameter_set.jl
  integration_tests/Manifest.toml
  integration_tests/Project.toml
  perf/Manifest.toml
  perf/Project.toml
  post_processing/mse_tables.jl
  src/EDMF_Environment.jl
  src/EDMF_Precipitation.jl
  src/EDMF_Updrafts.jl
  src/EDMF_functions.jl
  src/Parameters.jl
  src/TurbulenceConvection.jl
  src/TurbulenceConvectionParameters.jl
  src/closures/buoyancy_gradients.jl
  src/microphysics_coupling.jl
  src/thermodynamics.jl
  src/update_aux.jl
  test/Project.toml
Labels: ClimaParameters :control_knobs:, Dependencies :spider_web:

#1210 Fix parsed_args_from_cl_args
  integration_tests/cli_options.jl
Labels: bugfix

#1213 Fix ref state plots
  docs/src/PlotReferenceStates.jl
Labels: documentation
